services:
  bf4-server-watcher:
    build: .
    image: bf4-server-watcher:1.1.9
    container_name: BF4_ServerWatcher
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVERWATCHER_RUNTIME_DIR: /data
    volumes:
      - ./:/data
